services:
  nebula:
    container_name: nebula
    build: .
    ports:
      - 8888:8888
    depends_on:
      nebula_db:
        condition: service_started
    environment:
      - DOCKER=TRUE
      - PYTHONUNBUFFERED=1
      - SECRET_KEY=
      - CouchDB_PASSWORD=
      - GOOGLE_CLIENT_ID=

  nebula_db:
    image: postgres:latest
    container_name: nebula_db
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=nebula
    ports:
      - 5984:5984