services:
  nebula:
    container_name: nebula
    build: .
    ports:
      - 8888:8888
    depends_on:
      nebula_db:
        condition: service_started
    environment:
      - DOCKER=TRUE
      - PYTHONUNBUFFERED=1
      - CouchDB_PASSWORD=
      - GOOGLE_CLIENT_ID=

  nebula_db:
    image: couchdb:latest
    container_name: nebula_db
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984